/** @typedef {'json-stdio'|'ts-plugin'|'mcp-only'|'skills'} HookParadigm */
/** @typedef {{id:string,name:string,vendor:string,summary:string,instructionFile:string,mcpConfigPath:string,hookParadigm:HookParadigm,hooks:object,toolMap:Record<string,string>,install:string[],notes:string,compliance:number}} Adapter */

export const ADAPTERS = [
  {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    summary: "Highest fidelity. Six hook events, marketplace plugin, original Cowork path — now one adapter.",
    instructionFile: "CLAUDE.md",
    mcpConfigPath: "~/.claude.json → mcpServers",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: null,
    },
    toolMap: {
      Bash: "shell",
      Read: "read",
      Grep: "grep",
      WebFetch: "webfetch",
      Agent: "agent",
      Task: "task",
    },
    install: [
      "npx --yes --package=github:scottconverse/context-mode context-mode",
      "or: /plugin marketplace add scottconverse/context-mode",
      "/plugin install context-mode@scottconverse-context-mode",
    ],
    notes: "Keep the existing plugin install. The refactor only changes how the core is imported — CLAUDE.md becomes a generated instruction file, not the source of truth.",
    compliance: 98,
  },
  {
    id: "claude-cowork",
    name: "Claude Cowork",
    vendor: "Anthropic",
    summary: "Same hooks as Claude Code, registered through .claude-plugin/plugin.json and CLAUDE_PLUGIN_ROOT.",
    instructionFile: "CLAUDE.md",
    mcpConfigPath: ".claude-plugin/plugin.json → mcpServers",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: "SubagentStop",
    },
    toolMap: {
      Bash: "shell",
      Read: "read",
      Grep: "grep",
      WebFetch: "webfetch",
      Agent: "agent",
      Task: "task",
    },
    install: [
      "Keep plugin.json, but point mcpServers.command at the portable start.js",
      "Replace CLAUDE_PLUGIN_DATA fallbacks with CONTEXT_MODE_DATA",
    ],
    notes: "This is v1.6. The adapter extracts Cowork env vars behind a data-dir resolver so the core never mentions CLAUDE_PLUGIN_*.",
    compliance: 98,
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    summary: "Native preToolUse / postToolUse / stop. sessionStart is rejected — routing also lives in a .mdc rule.",
    instructionFile: ".cursor/rules/context-mode.mdc",
    mcpConfigPath: ".cursor/mcp.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "preToolUse",
      postToolUse: "postToolUse",
      preCompact: null,
      sessionStart: null,
      stop: "stop",
    },
    toolMap: {
      Shell: "shell",
      Read: "read",
      Grep: "grep",
      WebFetch: "webfetch",
      Task: "task",
    },
    install: [
      "Copy .cursor/mcp.json into the project (or ~/.cursor/mcp.json)",
      "Copy .cursor/rules/context-mode.mdc",
      "Optional: symlink the plugin into ~/.cursor/plugins/local/context-mode",
    ],
    notes: "Cursor manifests cannot reference ${PLUGIN_ROOT}. MCP must be npx -y context-mode or a pinned global install.",
    compliance: 85,
  },
  {
    id: "grok",
    name: "Grok / Grok Build",
    vendor: "xAI",
    summary: "No PreToolUse hooks. Instruction file + skill. Tool map covers the Grok Build sandbox tools.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "skills / connected MCP (when the host exposes it)",
    hookParadigm: "skills",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      run_terminal_command: "shell",
      read_file: "read",
      grep: "grep",
      browse_page: "webfetch",
      web_search: "webfetch",
      task: "agent",
    },
    install: [
      "Paste the generated AGENTS.md block into the project instruction file",
      "Drop .grok/skills/context-mode/SKILL.md so the agent loads it on tool-heavy turns",
      "Prefer ctx_execute patterns in the skill decision tree — the host will not intercept tools for you",
    ],
    notes: "Instruction-only adapters top out around 60% compliance. The skill is the enforcement surface until Grok grows hooks.",
    compliance: 60,
  },
  {
    id: "codex",
    name: "Codex CLI",
    vendor: "OpenAI",
    summary: "Full JSON hook set plus AGENTS.md. MCP in ~/.codex/config.toml.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "~/.codex/config.toml [mcp_servers]",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: "Stop",
    },
    toolMap: {
      shell: "shell",
      read_file: "read",
      grep_files: "grep",
      web_search: "webfetch",
      spawn_agent: "agent",
    },
    install: [
      "codex plugin marketplace add scottconverse/context-mode",
      "Enable plugin_hooks in Codex settings",
    ],
    notes: "Hook names match Claude's capitalization. Session id arrives as conversation_id.",
    compliance: 95,
  },
  {
    id: "copilot",
    name: "VS Code Copilot",
    vendor: "GitHub",
    summary: "Hooks via .github/hooks plus MCP in .vscode/mcp.json.",
    instructionFile: ".github/copilot-instructions.md",
    mcpConfigPath: ".vscode/mcp.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: "Stop",
    },
    toolMap: {
      runInTerminal: "shell",
      readFile: "read",
      grepSearch: "grep",
      fetchWeb: "webfetch",
    },
    install: [
      "Write .vscode/mcp.json from the generator",
      "Write .github/hooks/context-mode.json",
      "Add the instruction file under .github/copilot-instructions.md",
    ],
    notes: "Workspace-scoped. Commit the MCP and instruction files so every contributor gets the same routing.",
    compliance: 90,
  },
  {
    id: "copilot-cli",
    name: "GitHub Copilot CLI",
    vendor: "GitHub",
    summary: "camelCase hooks, AGENTS.md, MCP at ~/.copilot/mcp-config.json.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "~/.copilot/mcp-config.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "preToolUse",
      postToolUse: "postToolUse",
      preCompact: "preCompact",
      sessionStart: "sessionStart",
      stop: "agentStop",
    },
    toolMap: {
      bash: "shell",
      read: "read",
      grep: "grep",
      web: "webfetch",
    },
    install: ["Write ~/.copilot/mcp-config.json", "Drop AGENTS.md at the repo root"],
    notes: "Hook names are camelCase. The dispatcher lowercases before matching.",
    compliance: 90,
  },
  {
    id: "copilot-jetbrains",
    name: "JetBrains Copilot",
    vendor: "GitHub",
    summary: "Same hook names as VS Code Copilot. MCP registered in the IDE settings UI.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "Settings → Tools → AI Assistant → MCP",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: "Stop",
    },
    toolMap: {
      terminal: "shell",
      readFile: "read",
      findInFiles: "grep",
    },
    install: ["Add the MCP server in the IDE UI", "Commit AGENTS.md"],
    notes: "No project-level MCP file. Document the UI steps in the generated README.",
    compliance: 80,
  },
  {
    id: "opencode",
    name: "OpenCode",
    vendor: "SST",
    summary: "In-process TypeScript plugin. tool.execute.before/after plus compacting hook.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "opencode.json plugin array (no MCP block)",
    hookParadigm: "ts-plugin",
    hooks: {
      preToolUse: "tool.execute.before",
      postToolUse: "tool.execute.after",
      preCompact: "experimental.session.compacting",
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      bash: "shell",
      read: "read",
      grep: "grep",
      webfetch: "webfetch",
    },
    install: ["Add context-mode to the plugin array in opencode.json", "Commit AGENTS.md"],
    notes: "Runs in-process — no stdio MCP hop. SessionStart is emulated via experimental.chat.system.transform.",
    compliance: 88,
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    vendor: "Google",
    summary: "BeforeTool / AfterTool / PreCompress. Instruction file is GEMINI.md.",
    instructionFile: "GEMINI.md",
    mcpConfigPath: "~/.gemini/settings.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "BeforeTool",
      postToolUse: "AfterTool",
      preCompact: "PreCompress",
      sessionStart: "SessionStart",
      stop: null,
    },
    toolMap: {
      run_shell_command: "shell",
      read_file: "read",
      grep: "grep",
      web_fetch: "webfetch",
    },
    install: ["Merge MCP server into ~/.gemini/settings.json", "Write GEMINI.md at the repo root"],
    notes: "Hook names differ. The dispatcher maps BeforeTool → preToolUse before the core sees the event.",
    compliance: 90,
  },
  {
    id: "antigravity",
    name: "Antigravity IDE",
    vendor: "Google",
    summary: "MCP-only. No hooks — GEMINI.md is auto-written at the project root.",
    instructionFile: "GEMINI.md",
    mcpConfigPath: "~/.gemini/antigravity/mcp_config.json",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      run_command: "shell",
      read_file: "read",
      search: "grep",
    },
    install: ["Register MCP in antigravity mcp_config.json", "Commit GEMINI.md"],
    notes: "Instruction-only. Same 60% ceiling as other MCP-only hosts.",
    compliance: 60,
  },
  {
    id: "zed",
    name: "Zed",
    vendor: "Zed",
    summary: "context_servers in Zed settings. No hooks.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "~/.config/zed/settings.json → context_servers",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      terminal: "shell",
      read_file: "read",
      grep: "grep",
    },
    install: ["Add context_servers.context-mode to Zed settings", "Commit AGENTS.md"],
    notes: "Zed has no hook API. Do not pretend otherwise in the generated files.",
    compliance: 60,
  },
  {
    id: "continue",
    name: "Continue",
    vendor: "Continue",
    summary: "MCP via .continue/config.yaml. Instruction-only routing.",
    instructionFile: ".continue/config.yaml rules",
    mcpConfigPath: ".continue/config.yaml",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      runTerminalCommand: "shell",
      readFile: "read",
      grepSearch: "grep",
    },
    install: ["Add the MCP server block to .continue/config.yaml", "Add a rule that prefers ctx_* tools"],
    notes: "Continue rules fire as system prefixes, not intercepts.",
    compliance: 55,
  },
  {
    id: "windsurf",
    name: "Windsurf",
    vendor: "Codeium",
    summary: "Cascade rules file. No programmatic hooks.",
    instructionFile: ".windsurfrules",
    mcpConfigPath: "~/.codeium/windsurf/mcp_config.json",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      run_command: "shell",
      read_file: "read",
      grep: "grep",
      search_web: "webfetch",
    },
    install: ["Write .windsurfrules from the generator", "Register MCP if the Cascade MCP panel is enabled"],
    notes: "Treat as instruction-only until Windsurf documents a hook API.",
    compliance: 55,
  },
  {
    id: "aider",
    name: "Aider",
    vendor: "Aider",
    summary: "CONVENTIONS.md plus optional MCP. Aider has no hook bus.",
    instructionFile: "CONVENTIONS.md",
    mcpConfigPath: "optional — aider is typically in-process tools",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      run: "shell",
      read: "read",
      grep: "grep",
    },
    install: ["Write CONVENTIONS.md", "Add /read CONVENTIONS.md to the Aider launch"],
    notes: "Aider already keeps diffs tight. The value is the compressor on /run output and the knowledge base.",
    compliance: 50,
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    vendor: "OpenClaw",
    summary: "Native gateway plugin. api.on / api.registerHook. AGENTS.md.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "openclaw.json plugins.entries[context-mode]",
    hookParadigm: "ts-plugin",
    hooks: {
      preToolUse: "tool_call:before",
      postToolUse: "tool_call:after",
      preCompact: "registerContextEngine",
      sessionStart: "command:new",
      stop: null,
    },
    toolMap: {
      exec: "shell",
      read: "read",
      grep: "grep",
      fetch: "webfetch",
    },
    install: ["npm run install:openclaw -- /path/to/openclaw-state", "Confirm plugins.entries.context-mode"],
    notes: "In-process. Compaction goes through registerContextEngine rather than a PreCompact command hook.",
    compliance: 92,
  },
  {
    id: "kilo",
    name: "KiloCode",
    vendor: "Kilo",
    summary: "Same TypeScript plugin surface as OpenCode.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "kilo.json",
    hookParadigm: "ts-plugin",
    hooks: {
      preToolUse: "tool.execute.before",
      postToolUse: "tool.execute.after",
      preCompact: "experimental.session.compacting",
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      bash: "shell",
      read: "read",
      grep: "grep",
    },
    install: ["Add the plugin in kilo.json", "Commit AGENTS.md"],
    notes: "Share the OpenCode plugin module; only the manifest file name changes.",
    compliance: 88,
  },
  {
    id: "kiro",
    name: "Kiro",
    vendor: "AWS",
    summary: "preToolUse / postToolUse. agentSpawn is documented but not wired.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "~/.kiro/settings/mcp.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "preToolUse",
      postToolUse: "postToolUse",
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      executeCommand: "shell",
      readFile: "read",
      grep: "grep",
    },
    install: ["Write ~/.kiro/settings/mcp.json or .kiro/settings/mcp.json", "Commit AGENTS.md"],
    notes: "No PreCompact. Snapshot must be taken on postToolUse when context usage crosses a threshold.",
    compliance: 75,
  },
  {
    id: "qwen",
    name: "Qwen Code",
    vendor: "Alibaba",
    summary: "Claude-compatible hook names. settings at ~/.qwen/settings.json.",
    instructionFile: "QWEN.md",
    mcpConfigPath: "~/.qwen/settings.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: null,
    },
    toolMap: {
      Bash: "shell",
      Read: "read",
      Grep: "grep",
      WebFetch: "webfetch",
    },
    install: ["Merge MCP into ~/.qwen/settings.json", "Write QWEN.md"],
    notes: "Treat as a Claude-shaped adapter with a different instruction filename.",
    compliance: 95,
  },
  {
    id: "kimi",
    name: "Kimi Code",
    vendor: "Moonshot",
    summary: "Full JSON hook set. MCP at ~/.kimi-code/mcp.json.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: "~/.kimi-code/mcp.json",
    hookParadigm: "json-stdio",
    hooks: {
      preToolUse: "PreToolUse",
      postToolUse: "PostToolUse",
      preCompact: "PreCompact",
      sessionStart: "SessionStart",
      stop: "Stop",
    },
    toolMap: {
      Shell: "shell",
      Read: "read",
      Grep: "grep",
      WebFetch: "webfetch",
    },
    install: ["Write ~/.kimi-code/mcp.json", "Commit AGENTS.md"],
    notes: "Hook payload uses session_id. Same dispatcher as Claude.",
    compliance: 90,
  },
  {
    id: "pi",
    name: "Pi / Oh My Pi",
    vendor: "Pi",
    summary: "MCP-only. Instruction file PI.md. No hooks.",
    instructionFile: "PI.md",
    mcpConfigPath: "~/.omp/agent/mcp_config.json",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      bash: "shell",
      read: "read",
      grep: "grep",
    },
    install: ["Write mcp_config.json under the agent root", "Write PI.md"],
    notes: "Do not generate hook handlers. The adapter throws if asked to register one.",
    compliance: 55,
  },
  {
    id: "generic",
    name: "Any MCP client",
    vendor: "Generic",
    summary: "Fallback adapter. AGENTS.md + stdio MCP. Works anywhere the client can launch a server.",
    instructionFile: "AGENTS.md",
    mcpConfigPath: ".mcp.json",
    hookParadigm: "mcp-only",
    hooks: {
      preToolUse: null,
      postToolUse: null,
      preCompact: null,
      sessionStart: null,
      stop: null,
    },
    toolMap: {
      shell: "shell",
      bash: "shell",
      read: "read",
      grep: "grep",
      webfetch: "webfetch",
    },
    install: [
      "Drop .mcp.json next to the project (or in the client's MCP settings)",
      "Paste AGENTS.md into whatever instruction file the client reads",
    ],
    notes: "This is the 'any AI provider' floor. No hooks, MCP tools + a decision tree. Compliance depends on the model following the file.",
    compliance: 50,
  },
];

export function getAdapter(id) {
  return ADAPTERS.find((a) => a.id === id);
}

export function hookCount(a) {
  return Object.values(a.hooks).filter(Boolean).length;
}

export function reverseToolMap(a) {
  const out = {};
  for (const [provider, canonical] of Object.entries(a.toolMap)) {
    if (!out[canonical]) out[canonical] = provider;
  }
  return out;
}
